# Generated by Django 4.0.6 on 2022-07-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadisticas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadistica',
            name='subtotal',
            field=models.FloatField(verbose_name='Sub-Total'),
        ),
        migrations.AlterField(
            model_name='estadistica',
            name='total',
            field=models.FloatField(verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='estadistica',
            name='victorias',
            field=models.FloatField(verbose_name='Victorias'),
        ),
        migrations.AlterField(
            model_name='estadistica',
            name='win8',
            field=models.FloatField(verbose_name='Win8'),
        ),
    ]
