# Generated by Django 4.0.6 on 2022-08-07 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estadisticas', '0002_alter_estadistica_subtotal_alter_estadistica_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadistica',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='estadistica',
            name='total',
        ),
    ]
