# Generated by Django 4.0.6 on 2022-08-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadisticas', '0003_remove_estadistica_subtotal_remove_estadistica_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadistica',
            name='victorias',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Victorias'),
        ),
        migrations.AlterField(
            model_name='estadistica',
            name='win8',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Win8'),
        ),
    ]
