# Generated by Django 4.0.6 on 2022-08-07 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estadisticas', '0005_estadistica_subtotal_estadistica_total_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadistica',
            options={'ordering': ['tipo']},
        ),
    ]
