# Generated by Django 4.0.6 on 2022-08-14 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estadisticas', '0007_alter_estadistica_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadistica',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='estadistica',
            name='total',
        ),
    ]
