# Generated by Django 4.0.6 on 2022-08-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadisticas', '0008_remove_estadistica_subtotal_remove_estadistica_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadistica',
            name='batallas',
            field=models.FloatField(verbose_name='Batallas'),
        ),
        migrations.AlterField(
            model_name='estadistica',
            name='experiencia',
            field=models.FloatField(verbose_name='Experiencia'),
        ),
    ]
