# Generated by Django 4.0.6 on 2022-08-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadisticas', '0009_alter_estadistica_batallas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadistica',
            name='batallas',
            field=models.IntegerField(verbose_name='Batallas'),
        ),
        migrations.AlterField(
            model_name='estadistica',
            name='experiencia',
            field=models.IntegerField(verbose_name='Experiencia'),
        ),
    ]
