# Generated by Django 4.0.6 on 2022-08-15 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estadisticas', '0011_estadistica_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadistica',
            name='subtotal',
        ),
    ]
