# Generated by Django 4.0.6 on 2022-08-15 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estadisticas', '0012_remove_estadistica_subtotal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadistica',
            options={'ordering': ['nombre']},
        ),
    ]
