# Generated by Django 4.0.6 on 2022-08-15 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estadisticas', '0014_alter_estadistica_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadistica',
            options={'ordering': [2.718281828459045]},
        ),
    ]
