# Generated by Django 4.0.6 on 2022-08-16 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estadisticas', '0016_alter_estadistica_options_estadistica_subtotal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadistica',
            options={'ordering': ['nivel']},
        ),
        migrations.RemoveField(
            model_name='estadistica',
            name='subtotal',
        ),
    ]
