# Generated by Django 4.0.6 on 2022-08-16 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estadisticas', '0018_estadistica_subtotal_estadistica_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadistica',
            options={'ordering': ['batallas']},
        ),
        migrations.RemoveField(
            model_name='estadistica',
            name='experiencia',
        ),
        migrations.RemoveField(
            model_name='estadistica',
            name='nivel',
        ),
        migrations.RemoveField(
            model_name='estadistica',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='estadistica',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='estadistica',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='estadistica',
            name='total',
        ),
        migrations.RemoveField(
            model_name='estadistica',
            name='victorias',
        ),
        migrations.RemoveField(
            model_name='estadistica',
            name='win8',
        ),
    ]
