# Generated by Django 4.0.6 on 2022-08-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadisticas', '0019_alter_estadistica_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadistica',
            options={'ordering': ['nivel']},
        ),
        migrations.AddField(
            model_name='estadistica',
            name='experiencia',
            field=models.IntegerField(default=1, verbose_name='Experiencia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estadistica',
            name='nivel',
            field=models.IntegerField(default=1, verbose_name='Nivel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estadistica',
            name='nombre',
            field=models.CharField(default=1, max_length=50, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estadistica',
            name='pais',
            field=models.CharField(default=1, max_length=20, verbose_name='Pais'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estadistica',
            name='tipo',
            field=models.CharField(default=1, max_length=15, verbose_name='Tipo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estadistica',
            name='total',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='estadistica',
            name='victorias',
            field=models.FloatField(default=1, verbose_name='Victorias'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estadistica',
            name='win8',
            field=models.FloatField(default=1, verbose_name='Win8'),
            preserve_default=False,
        ),
    ]
