# Generated by Django 4.0.6 on 2022-08-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadisticas', '0020_alter_estadistica_options_estadistica_experiencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadistica',
            name='garaje',
            field=models.BooleanField(default=False),
        ),
    ]
