# Generated by Django 4.0.6 on 2022-08-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadisticas', '0021_estadistica_garaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadistica',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
