# Generated by Django 4.0.6 on 2022-07-28 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estadistica',
        ),
    ]
