# Generated by Django 4.0.6 on 2022-08-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='win8',
            name='actual',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='win8',
            name='mejor',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='win8',
            name='peor',
            field=models.FloatField(),
        ),
    ]
