# Generated by Django 4.0.6 on 2022-08-21 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0005_tanques'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tanques',
            new_name='Tanque',
        ),
    ]
