# Generated by Django 4.0.6 on 2022-08-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0006_rename_tanques_tanque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanque',
            name='numero',
            field=models.IntegerField(unique=True),
        ),
    ]
