# Generated by Django 4.0.6 on 2022-08-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0007_alter_tanque_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanque',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
