# Generated by Django 4.0.6 on 2022-08-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repeticione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('tipo', models.CharField(max_length=15, verbose_name='Tipo')),
                ('pais', models.CharField(max_length=20, verbose_name='Pais')),
                ('nivel', models.IntegerField(verbose_name='Nivel')),
                ('destruidos', models.IntegerField(verbose_name='Destruidos')),
                ('causado', models.IntegerField(verbose_name='Daño Causado')),
                ('bloqueado', models.IntegerField(verbose_name='Daño Bloqueado')),
                ('detectado', models.IntegerField(verbose_name='Daño Detectado')),
                ('aturdimiento', models.IntegerField(verbose_name='Daño Aturdimiento')),
                ('video', models.FileField(upload_to='repeticiones', verbose_name='Video')),
            ],
            options={
                'ordering': ['nivel'],
            },
        ),
    ]
